{% set name = "abess" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fce0dcbac8d3ab04289b3a29780e45848754f2a7948caf3ad7fa5cb10dfc031

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - make
    - cmake
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - intel-openmp  # [win]
  host:
    - pip
    - setuptools
    - python
    - numpy
    - pybind11 >=2.6.0
  run:
    - scipy
    - pandas
    - scikit-learn >=0.24
    - python

test:
  imports:
    - abess
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://abess.readthedocs.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fast Best-Subset Selection
  description: |
    abess (Adaptive BEst-Subset Selection) library aims to solve general best subset selection, i.e., 
    find a small subset of predictors such that the resulting model is expected to have the highest accuracy. 
    This library implements a generic algorithm framework to find the optimal solution in an extremely fast way. 
    This framework now supports the detection of best subset under: 
    linear regression, (multi-class) classification, censored-response modeling, 
    multi-response modeling (a.k.a. multi-tasks learning), etc. 
    It also supports the variants of best subset selection like group best subset selection. 
    Especially, the time complexity of (group) best subset selection for linear regression is certifiably polynomial.
  doc_url: https://abess.readthedocs.io
  dev_url: https://github.com/abess-team/abess

extra:
  recipe-maintainers:
    - oooo26
    - Mamba413
